## 1.1 arange
- array의 범위를 지정하여, 값의 List를 생성하는 명령어

In [1]:
import numpy as np

In [2]:
np.arange(30) # range: List의 range와 같은 효과, integer로 0부터 ~ 29까지 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
np.arange(0,5,0.5) # floating point도 표시가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [4]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
np.arange(30).reshape(2,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## 1.2 ones,zeros and empty

In [6]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((2,5)) # 2 by 5 - ones matrix 생성

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.empty((5,5)) # 5 by 5 -empty matrix를 생성하는데 선언과 동시에 초기화를 시켜주지 않는다.

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.78019761e-306,
        1.78019761e-306, 1.20160711e-306],
       [1.78020169e-306, 1.42418172e-306, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307],
       [8.90111708e-307, 2.11389826e-307, 1.11260619e-306,
        8.45610230e-307, 0.00000000e+000]])

## 1.3 something_like
- 기존에 있던 Matrix와 같은 shape 크기 만큼 1,0 또는 empty array를 반환

In [9]:
test_matrix = np.arange(30).reshape(5,6)

In [10]:
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [11]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## 1.4 identity
- 단위 행렬(i 행렬)을 생성

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 1.5 eye
- 대각선인 1인 행렬, k값의 시작 index의 변경이 가능

In [13]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [14]:
np.eye(3,5,k=2) # k: start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.eye(3) # = identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 1.6 diag
- 대각 행렬을 추출

In [16]:
a = np.arange(25).reshape(5,5)

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
np.diag(a) # a 변수의 대각 원소들을 추출

array([ 0,  6, 12, 18, 24])

## 1.7 random sampling

In [19]:
# 0 ~ 1 사이의 균등분포 10개의 값들을 샘플링 
np.random.uniform(0,1,10).reshape(2,5)

array([[0.8729557 , 0.35670865, 0.80321431, 0.60275024, 0.11177329],
       [0.88562334, 0.97613354, 0.39678023, 0.34813632, 0.55255551]])

In [20]:
# 0 ~ 1 사이의 정규분포 10개의 값들을 샘플링
# 평균이 0이고, 정규분포가 1인 10개의 값들을 샘플링
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.55292381,  1.34690501,  0.1826733 ,  1.00732831, -0.75040307],
       [-0.15374027,  0.97544238,  1.15375602,  1.73550937,  0.68383882]])

# 2. operation functions
- 넘파이의 계산함수

## 2.1 sum

In [21]:
test_array = np.arange(1,11)

In [22]:
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
test_array.sum() # dtype 지정 

55

## 2.2 axis
- 모든 operation function을 실행할 때 기준이 되는 dimension 축
![test](./img/axis.png)


In [24]:
test_array = np.arange(1,13).reshape(3,4)

In [25]:
test_array.sum(axis=1) # 기존의 벡터 즉, 벡터를 기준으로

array([10, 26, 42])

In [26]:
test_array.sum(axis=0) # row 축을 기준으로 

array([15, 18, 21, 24])

In [27]:
test_array1 = np.array([1,2,3,4])

In [28]:
test_array1.shape

(4,)

In [29]:
test_array1.sum(axis=0)

10

In [30]:
test_array2 = np.arange(0,20).reshape(2,2,5)

In [31]:
test_array2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [32]:
test_array2.shape

(2, 2, 5)

In [33]:
test_array2.sum(axis=2) # 벡터의 형태를 기준

array([[10, 35],
       [60, 85]])

In [34]:
test_array2.sum(axis=1) # 열의 축을 기준으로

array([[ 5,  7,  9, 11, 13],
       [25, 27, 29, 31, 33]])

In [35]:
test_array2.sum(axis=0) # matrix 형태로 변형

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

![test](./img/axis2.png)

In [36]:
test_array = np.arange(1,13).reshape(3,4)

## 2.3 mean & std

In [37]:
test_array.mean()

6.5

In [38]:
test_array.std()

3.452052529534663

## 2.4 Mathematical functions
![test](./img/연산자.png)

## 2.5 concatenate
- Numpy array를 합치는 함수
![test](./img/concat.png)

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b)) #넘파이 배열을 수직적으로 합친다

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b)) # 넘파이를 수평적으로 합친다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.concatenate((a,b),axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [43]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

# 3. array operations
## 3.1 Operation b/t array
- numpy는 array간의 기본적인 사칙연산을 지원한다.


In [44]:
test_a = np.array([[1,2,3],[4,5,6]])

In [45]:
test_a+test_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [46]:
test_a - test_a

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
test_a * test_a # 행렬의 곱이 아닌 같은 위치에 있는 원소끼리 곱하는 것

array([[ 1,  4,  9],
       [16, 25, 36]])

## 3.2 Dot product
- Matrix의 기본 연사
- dot 함수 사용

In [48]:
test_a = np.array([[1,2,3],[4,5,6]])
test_b = np.array([[1,2,],[1,2],[1,2]])

In [49]:
np.dot(test_a,test_b)

array([[ 6, 12],
       [15, 30]])

In [50]:
test_a.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

## 3.3 broadcasting
- shape이 다른 배열 간 연산을 자동으로 지원하는 기능
- Scaler, vector 외에도 matrix간의 연산도 지원

In [51]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
test_a + 3 # 3이 각각의 위치에서 자동으로 더해준다.

array([[4, 5, 6],
       [7, 8, 9]])

In [53]:
test_a * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [55]:
test_a **2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [56]:
test_a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
test_b = np.array([[1,2,3]])

In [58]:
test_a + test_b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [59]:
test_c = np.array([[10],[20],[30],[40]])
test_d = np.array([[10,20,30]])

In [60]:
test_c+test_d

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70]])

# 4. comparisons
## 4.1 All & Any
- array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [69]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a > 5 # broadcasting 처럼 comparisons 했을때 출력을 리스트 형식으로 반환

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [64]:
np.any(a>5) # 하나라도 조건에 만족한다면 true

True

In [65]:
np.any(a<0)

False

In [66]:
np.all(a>5) # 모두가 조건에 만족한다면 true

False

In [68]:
np.all(a>-1)

True

In [71]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)

In [72]:
test_a > test_b

array([False,  True, False])

In [73]:
test_a == test_b

array([False, False, False])

In [74]:
(test_a > test_b).any()

True

In [75]:
a = np.array([1,3,0],float)
np.logical_and(a>0,a<3) # and 조건의 condition

array([ True, False, False])

In [76]:
np.logical_or(a>0,a<3) # or 조건의 condition

array([ True,  True,  True])

## 4.2 np.where

In [77]:
np.where(a>0,3,2) # where(condition,True,False)

array([3, 3, 2])

In [78]:
a = np.arange(10)
np.where(a>5) # index 값 반환

(array([6, 7, 8, 9], dtype=int64),)

In [79]:
a = np.arange(5,15)

In [80]:
a > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [82]:
np.where(a>10) # true 인 값의 index 값을 추출

(array([6, 7, 8, 9], dtype=int64),)

## 4.3 argmax & argmin
- array내 최대값 또는 최소값의 index를 반환

In [83]:
a = np.array([1,2,4,5,8,78,23,3])

In [84]:
np.argmax(a) # 78의 index를 반환

5

In [85]:
np.argmin(a) # 1의 index를 반환

0

In [86]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])

In [87]:
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [88]:
np.argmax(a,axis=1) # 행 기준

array([3, 1, 1], dtype=int64)

In [89]:
np.argmax(a,axis=0) # 열 기준

array([1, 1, 1, 1], dtype=int64)

# 5. boolean & fancy index

## 5.1 boolean index
- numpy의 배열은 특정 조건에 따른 값을 배열 형태로 추출 할 수 있다.
- comparison operation 함수들도 모두 사용 가능

In [90]:
test_array = np.array([1,4,0,2,3,8,9,7])
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [91]:
test_array[test_array>3] # 조건이 True인 index의 element만 추출

array([4, 8, 9, 7])

In [92]:
condition = test_array < 3

In [94]:
test_array[condition]

array([1, 0, 2])

In [95]:
condition.astype(np.int) # True = 1, False = 0

array([1, 0, 1, 1, 0, 0, 0, 0])

## 5.2 fancy index
- numpy의 array를 index value로 사용해서 값을 추출하는 방법

In [96]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,1,3,2,1],int) # 반드시 integer로 선언
a[b] # bracket index, b배열의 값을 index로 하여 a의 값들을 추출

array([2., 2., 4., 8., 6., 4.])

In [97]:
a.take(b) # take 함수: bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [99]:
a = np.array([[1,4],[9,16]])
b = np.array([0,0,1,1,0],int)
c = np.array([0,1,1,1,1],int)

In [100]:
a[b,c]

array([ 1,  4, 16, 16,  4])