# 1. Numpy
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준

## 1.1 Numpy 특징
- 일반 List에 비해 빠르고, 메모리에 효율적
- 반목문 없이 데이터 배열에 대한 처리를 지원
- 선형대수와 관련된 다양한 기능을 제공

## 1.2 ndarray



In [1]:
import numpy as np

In [3]:
test_arry = np.array([1,2,3,4],float) # 다양한 자료형을 선언 할 수 있다.
print(test_arry)

[1. 2. 3. 4.]


- numpy는 하나의 데이터 type만 배열에 넣을 수 있다.
- List와 가장 큰 차이점, Dynamic typing not supported

In [4]:
type(test_arry[3]) # float(3번째 인덱스 자료 type 반환)

numpy.float64

In [5]:
test_arry.dtype # 전체 데이터 Type을 반환

dtype('float64')

### 넘파이 vs 리스트

![test](./img/넘파이1.png)

- 넘파이는 정해진 공간에 할당되는 반면, 리스트는 주소 값으로 저장되기 때문에 속도가 느리다.

![test](./img/넘파이2.png)

## 1.3 Array shape(vector)
- Array (vector,matrix,tensor)의 크기, 형태 등에 대한 정보

In [7]:
test_arry.shape # 넘파이의 dimention을 반환, 1차원에 원소의 갯수가 4개 즉, 벡터이고 element=4

(4,)

In [10]:
matrix = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [11]:
matrix

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
matrix.shape

(3, 4)

In [16]:
tensor = np.array([[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
         [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
         [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [17]:
tensor.shape

(4, 3, 4)

![test](./img/넘파이3.png)

- 4개의 Matrix와 3개의 row와 4개의 colums

## 1.4 Array shape - ndim & size
- ndim: number of dimension
- size: data의 개수

In [18]:
tensor.ndim # 차원 수: 3차원

3

In [19]:
tensor.size # data의 총 개수

48

## 1.5 Array dtype
- Ndarray의 single element가 가지는 data type
- 각 element가 차지하는 memory의 크기가 결정

In [20]:
np.array([[1,2,3],[4.5,5,6]],dtype=int) # 4byte 

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.array([[1,2,3],[4.5,5,6]],dtype=np.float64) # 8byte/ float32 4byte

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

## 1.6 reshape
- Array의 shape의 크기를 변경 (element의 갯수는 동일)

In [27]:
test_matrix = np.array([[1,2,3,4],[1,2,5,8]])

In [28]:
test_matrix # (2,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [24]:
test_matrix.reshape(4,2) # element갯수만 같다면 reshape을 시켜줄 수 있다.

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [29]:
test_matrix.reshape(-1,2).reshape # -1: size를 기반으로 row 개수 선정

<function ndarray.reshape>

In [32]:
a = test_matrix.reshape(2,2,2)

In [33]:
a.size

8

In [34]:
a.reshape(-1,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [35]:
a.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [39]:
a = np.array([[1,2,3],[4,5,6]])

In [41]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

## 1.7 indexing

In [48]:
a = np.array([[1,2,3],[4,5,6]])

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a[0,0] # (0,0) 위치의 인덱스 반환

1

In [51]:
a[0,0] = 10 #(0,0) 위치의 인덱스에 10 할당

## 1.8 Slicing

In [52]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [53]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
a[:,2:] # 전체 Row의 2열 이상

array([[3, 4],
       [7, 8]])

In [55]:
a[1,1:3] # 1 Row의 1열 ~ 2열

array([6, 7])

In [58]:
a[1:2] # 1Row ~ 2Row 전체

array([[5, 6, 7, 8]])

- List와 달리 행과 열 부분을 나눠서 슬라이싱이 가능하다.
- matrix의 부분 집합을 추출 할때 유용하다.


In [60]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]])

In [61]:
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [62]:
test_example[:2]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [64]:
test_example[:3,1:3] # 1Row~3Row 중에서 2열과 3열 추출

array([[2, 5],
       [2, 5],
       [2, 5]])

In [66]:
test_example[1,:2]

array([1, 2])

In [67]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [68]:
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [69]:
test_example[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [70]:
test_example[1,1:3] # 1Row의 1열,2열 추출

array([7, 8])

In [72]:
test_example[:,1:2] # 전체 Row의 2열 추출

array([[2],
       [7]])

In [73]:
test_example[:,::2] # 전체 Row의 시작점 끝점 2칸씩

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [75]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,1,1,1,1]])

In [78]:
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  1,  1,  1,  1]])

In [77]:
test_example[::2,::2]

array([[1, 3, 5],
       [1, 1, 1]])